### PR TITLE
Remove ‘authorise’ and just talk about using servers.

### PR DESCRIPTION
**Pull request by saradickinson**

### CODE REVIEW

**Comment by roryhewitt** [comment]
Sorry, I may be late to this party...

I'm not keen on the use of `MUST` and `MUST NOT` when discussing which DNS servers a client should choose/trust - those terms are used when discussing technical implementation details, and choosing whether to trust a DNS server isn't that - per RFC2119:

`MUST   This word, or the terms "REQUIRED" or "SHALL", mean that the definition is an absolute requirement of the specification.`

Additionally, without providing an explicit means of determining *how and whether* a DNS server is trusted, we're not really helping - we're just saying that the client MUST make that determination, with no further details.

I'd be fine with replacing them with lower-case non-normative `must` and/or `should`, e.g.:

> Before using a DNS API server for DNS resolution, the client must establish that
the HTTP request URI is a trusted service for the DOH query; in other words, a
DNS API client should only use a DNS API server that is determined to be trustworthy.
> 
> A client should not use a DNS API server simply because it was discovered, or
because the client was told to use the DNS API server by an untrusted party.
> 
> This specification does not extend DNS resolution privileges to URIs that are
not recognized by the DNS API client as trusted DNS API servers. As such, use of
untrusted servers is out of scope of this document.

**Comment by mcmanus** [comment]
@roryhewitt its actually not uncommon to leave the ultimate decision about trust out of a protocol definition while still saying that the protocol needs to make such a distinction. HTTPS is the most obvious example - in the end there are not rules about what certificate root to honor, how to annotate it, etc.. those are decisions implementations make.

**Comment by roryhewitt** [comment]
@mcmanus Yes, but if a client chooses to make bad decisions and trust a DNS server that they haven't 'vetted', then are they actually in contravention of this specification?

Actually, I guess it's really my second point that's in some ways the most important - typically a MUST/REQUIRED/SHALL specifies an action to take and there will be some obvious consequences for not taking that action (an error thrown). In this case, we're saying "You MUST check that the DNS server you want to connect to is trustworthy" without saying *how* they should do that. And since there will be no error message from an untrustworthy DNS server, how would they know?

It feels like we're taking things that outside of the spec (whether/how to trust a DNS server) and making it part of the spec...

**Comment by bemasc** [comment]
@roryhewitt MUST has many purposes.  One of them is to avoid confusion.  There's been a lot of concern during the DOH process that DOH clients will spray queries to random webservers, or otherwise violate security common sense.  This "requirement" is intended to respond to those concerns, and clarify that we are not proposing to do anything reckless.

**Comment by roryhewitt** [comment]
Well OK then.  I'm still not entirely happy, but if the consensus is to leave it as it is, I'm not going to push it.

**Comment by matjon** [comment]
I have moved the discussion to the mailing list:
https://www.ietf.org/mail-archive/web/doh/current/msg00557.html

**Pull request merged**
