### PR TITLE
can weaken the privacy and authenticity expected by the user

### PR DESCRIPTION
**Pull request by emanjon**
added authenticity

### CODE REVIEW

**Comment by martinthomson** [comment]
The potential for misunderstanding here is great.  If we consider authenticity to be stated as a goal, we would need more explicit about the properties that this provides.  Specifically, this does not provide authenticity with respect to responses, because that is the purpose of DNSSEC.

**Comment by emanjon** [comment]
Yes, that is true. Thinking about it, I think a web application developer (one of the targets) reading this draft might not fully understand the differences between authenticity at the HTTP layer and authenticity at the DNS layer. One of the stated features of Secure Contexts is authenticated channels that guarantee data integrity. If possible, I think a few more sentences elaborating on this topic would not hurt.

**Comment by paulehoffman** [comment]
I'm going to close this because we have no idea what kind of authentication that a user would expect, whereas we know pretty well what kind of privacy they expect.

**Comment by mcmanus** [comment]
I think there might be room for something different along these lines. DNS hijack from your configured DNS server is currently a major problem, and DoH does allow you to authenticate whether or not you are talking to your configured recursive (while not saying anything about e2e). I'm going to reopen to track..

**Pull request merged**
