### PR TITLE
Be more explicit about clients' interaction with the HTTP freshness

### LINKED ISSUE #14: Define the caching model
The draft doesn't really tackle the question of caching fully right now.  I think that there is an implied hierarchy of caches that are in use.

The query first hits the DNS stack, which maintains its own cache.  Using the DNS TTL, that cache might decide to answer the query.

Then there is an HTTP stack, which might maintain its own cache.  Notably, none of the HTTP cache-busting techniques work from the perspective of the DNS client, so we have to be careful to observe that.  This particularly ordering makes #13 much worse.

Finally, a DNS API server might maintain its own cache.

### PR DESCRIPTION
**Pull request by paulehoffman**
Fixes #14

### CODE REVIEW

**Comment by paulehoffman** [comment]
There are plenty of reasons to "extend" a TTL, such as if the TTL is below a configured threshold or if one cannot reach the authoritative server again. The rules for TTLs is (again...) being actively debated in the DNSOP WG, and it would be inappropriate for DOH to be more restrictive than DNS itself, thus the "SHOULD".

**Comment by martinthomson** [comment]
Leaving a bare "SHOULD" there asks more questions than this text answers.  If the considerations for extension are equivalent to those that apply to DNS, then saying that would help a lot.

**Comment by paulehoffman** [comment]
I hear that, but I'm at a loss of what words to use, given that the words don't exist in the DNS specs either. What is important to me is that we don't do more than the DNS specs, as vague as they are.

**Comment by martinthomson** [comment]
If implementations routinely (or otherwise) ignore the TTL, why not then say MUST?  Then it's clear what the TTL is, and now they are just ignoring the TTL (as per normal DNS practice).

**Comment by paulehoffman** [comment]
Good point, will fix before pulling.

**Comment by mcmanus** [comment]
@paulehoffman can you give a review here? github apparently won't let me ask you directly because you created the PR (which I seriously amended)

**Pull request merged**
