### PR TITLE
Deal with 512 byte limit and truncation

### PR DESCRIPTION
**Pull request by paulehoffman**
Related to #110

### CODE REVIEW

**Comment by mcmanus** [comment]
this is a strict improvement. let's merge and we can adjust further if there is feedback

**Comment by bortzmeyer** [comment]
No limit? Not even the UDP 64 k limit?

**Comment by bortzmeyer** [comment]
I would delete the "over TCP" in "DNS API server was not able to retrieve a full answer for the query over TCP" The DoH server is supposed to do its best to get the fuil answer, it does not mean we force TCP.

**Comment by paulehoffman** [comment]
Good catches. Will update with https://github.com/dohwg/draft-ietf-doh-dns-over-https/pull/123

**Comment by vttale** [comment]
I don't see a compelling technical reason to set a limit.

**Pull request merged**
