### PR TITLE
Make it clearer that this is local configuration

### PR DESCRIPTION
**Pull request by paulehoffman**

### CODE REVIEW

**Comment by mcmanus** [comment]
I think this actually confuses things depending on your definition of local.. for example we said that DHCP-like things could be in scope for configuration, are they local in scope?

I think simply configuration is fine - that's where the client determines policy. It doesn't come in the form of unsolicited data from the web which is what the rest of the paragraph says.

**Comment by paulehoffman** [comment]
DHCP-like things are indeed local in scope, so I think "local" still applies here. However, if you think changing "local" to "client", that's fine.

**Comment by mcmanus** [comment]
the existing text already says client configuration - that;'s why I tihnk it's fine.

**Comment by paulehoffman** [comment]
True, true. I'll close this.

**Pull request closed without merging**
